name: l4d2_vpk_manager
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    - flet==0.24.1
    - flet-core==0.24.1
    - flet-runtime==0.24.1
    - requests>=2.32.5
    - pyyaml>=6.0.3
    - python-dotenv>=1.2.1
