name: l4d2_vpk_manager
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    - flet==0.28.3
    - requests>=2.32.5
    - pyyaml>=6.0.3
    - python-dotenv>=1.2.1
    - py7zr>=0.20.0
    - vpk>=1.4.0    
    - zstandard>=0.21.0